### ISSUE TITLE
Slf4jAdapter should skip formatting/decoration/logging if level is not enabled

### ISSUE THREAD

**Issue by moldowan** [jcabi/jcabi-maven-slf4j#3]
Currently, Slf4jAdapter formats/decorates/logs right away. This imposes unnecessary overhead in case e.g. debug(...) is called but DEBUG level is not enabled at all.
Slf4jAdapter  should therefore check is...Enabled() before performing any further steps.

**Comment by yegor256** [comment]
@moldowan I suggest we leave it as is, since `isDebugEnabled` already provided in the public API. I believe, it's the job of the user to check it.
