### ISSUE TITLE
not able to write to a file

### ISSUE THREAD

**Issue by agnadesai** [jcabi/jcabi-maven-slf4j#6]
I am not able to write the log to a file.
http://stackoverflow.com/questions/28181730/jcabi-is-not-logging-in-a-file

**Comment by yegor256** [comment]
@agnadesai to help you out I will need more information. What exactly do you see in terminal when you run your app?

**Comment by agnadesai** [comment]
Hi @yegor256  my question is if can we use com.jcabi.log.Logger to write log to a file? I tried following but it doesn't work. 

# Direct log messages to a log file
log4j.appender.file=org.apache.log4j.RollingFileAppender
log4j.appender.file.File=D:\\log1.out
log4j.appender.file.MaxFileSize=10MB
log4j.appender.file.MaxBackupIndex=10
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c:%L - %m%n

**Comment by yegor256** [comment]
@agnadesai yes, we can use jcabi Logger to write to a file, but our logger has nothing to do with the file itself. All Logger is doing is transferring your calls to SLF4J. Then, SLF4J sends them to LOG4J, and then LOG4J writes to the file. You have a problem somewhere in the middle of this chain.

**Comment by agnadesai** [comment]
@yegor256 Hi I got it resolved I had my log4j not configured correctly. Thank you for your help.

**Comment by yegor256** [comment]
@agnadesai please close the ticket. you're welcome :)
