### ISSUE TITLE
Estimate project size

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-maven-slf4j#7]
There is no estimate in the project yet. We have to create one as explained [here](https://github.com/teamed/est)

**Comment by dmarkov** [comment]
@super132 it's your task, go ahead

**Comment by super132** [comment]
@dmarkov PR #10 fixed this issue, would you please close it? Thanks.

**Comment by yegor256** [comment]
@rultor deploy

**Comment by dmarkov** [comment]
@yegor256 Thanks all, I am closing

**Comment by dmarkov** [comment]
@super132 Thanks so much! Your account was topped up for **30 mins** (transaction ID is `AP-66256291UM314081A`, the task took 167 hours and 6 mins)

+30 added to your rating, at the moment it is: [+451](http://www.netbout.com/b/35282?open=rating)
